# Generated by Django 4.2.13 on 2024-07-15 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=8)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
